/**
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.building.impl;

import kcl.ac.uk.jian.building.building.AddFloorProcess;
import kcl.ac.uk.jian.building.building.BuildingPackage;
import kcl.ac.uk.jian.building.building.Expression;
import kcl.ac.uk.jian.building.building.WholeStructure;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Floor Process</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link kcl.ac.uk.jian.building.building.impl.AddFloorProcessImpl#getStructure <em>Structure</em>}</li>
 *   <li>{@link kcl.ac.uk.jian.building.building.impl.AddFloorProcessImpl#getLevels <em>Levels</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AddFloorProcessImpl extends ProcessImpl implements AddFloorProcess
{
  /**
   * The default value of the '{@link #getStructure() <em>Structure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructure()
   * @generated
   * @ordered
   */
  protected static final WholeStructure STRUCTURE_EDEFAULT = WholeStructure.ABOVEGROUND;

  /**
   * The cached value of the '{@link #getStructure() <em>Structure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructure()
   * @generated
   * @ordered
   */
  protected WholeStructure structure = STRUCTURE_EDEFAULT;

  /**
   * The cached value of the '{@link #getLevels() <em>Levels</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevels()
   * @generated
   * @ordered
   */
  protected Expression levels;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddFloorProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BuildingPackage.Literals.ADD_FLOOR_PROCESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WholeStructure getStructure()
  {
    return structure;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStructure(WholeStructure newStructure)
  {
    WholeStructure oldStructure = structure;
    structure = newStructure == null ? STRUCTURE_EDEFAULT : newStructure;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BuildingPackage.ADD_FLOOR_PROCESS__STRUCTURE, oldStructure, structure));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getLevels()
  {
    return levels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLevels(Expression newLevels, NotificationChain msgs)
  {
    Expression oldLevels = levels;
    levels = newLevels;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BuildingPackage.ADD_FLOOR_PROCESS__LEVELS, oldLevels, newLevels);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevels(Expression newLevels)
  {
    if (newLevels != levels)
    {
      NotificationChain msgs = null;
      if (levels != null)
        msgs = ((InternalEObject)levels).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BuildingPackage.ADD_FLOOR_PROCESS__LEVELS, null, msgs);
      if (newLevels != null)
        msgs = ((InternalEObject)newLevels).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BuildingPackage.ADD_FLOOR_PROCESS__LEVELS, null, msgs);
      msgs = basicSetLevels(newLevels, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BuildingPackage.ADD_FLOOR_PROCESS__LEVELS, newLevels, newLevels));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BuildingPackage.ADD_FLOOR_PROCESS__LEVELS:
        return basicSetLevels(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BuildingPackage.ADD_FLOOR_PROCESS__STRUCTURE:
        return getStructure();
      case BuildingPackage.ADD_FLOOR_PROCESS__LEVELS:
        return getLevels();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BuildingPackage.ADD_FLOOR_PROCESS__STRUCTURE:
        setStructure((WholeStructure)newValue);
        return;
      case BuildingPackage.ADD_FLOOR_PROCESS__LEVELS:
        setLevels((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BuildingPackage.ADD_FLOOR_PROCESS__STRUCTURE:
        setStructure(STRUCTURE_EDEFAULT);
        return;
      case BuildingPackage.ADD_FLOOR_PROCESS__LEVELS:
        setLevels((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BuildingPackage.ADD_FLOOR_PROCESS__STRUCTURE:
        return structure != STRUCTURE_EDEFAULT;
      case BuildingPackage.ADD_FLOOR_PROCESS__LEVELS:
        return levels != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (structure: ");
    result.append(structure);
    result.append(')');
    return result.toString();
  }

} //AddFloorProcessImpl
