/**
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.building.impl;

import kcl.ac.uk.jian.building.building.BuildingPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProcessImpl extends MinimalEObjectImpl.Container implements kcl.ac.uk.jian.building.building.Process
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BuildingPackage.Literals.PROCESS;
  }

} //ProcessImpl
