/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBuildingValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(kcl.ac.uk.jian.building.building.BuildingPackage.eINSTANCE);
		return result;
	}
}
