/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kcl.ac.uk.jian.building.BuildingRuntimeModule;
import kcl.ac.uk.jian.building.BuildingStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BuildingIdeSetup extends BuildingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BuildingRuntimeModule(), new BuildingIdeModule()));
	}
	
}
