/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.ui;

import com.google.inject.Injector;
import kcl.ac.uk.jian.building.ui.internal.BuildingActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BuildingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BuildingActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BuildingActivator activator = BuildingActivator.getInstance();
		return activator != null ? activator.getInjector(BuildingActivator.KCL_AC_UK_JIAN_BUILDING_BUILDING) : null;
	}

}
