/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BuildingRuntimeModule extends AbstractBuildingRuntimeModule {
}
