/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBuildingScopeProvider extends DelegatingScopeProvider {
}
