/**
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.building;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Window Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.ac.uk.jian.building.building.AddWindowProcess#getNum <em>Num</em>}</li>
 *   <li>{@link kcl.ac.uk.jian.building.building.AddWindowProcess#getLevels <em>Levels</em>}</li>
 * </ul>
 *
 * @see kcl.ac.uk.jian.building.building.BuildingPackage#getAddWindowProcess()
 * @model
 * @generated
 */
public interface AddWindowProcess extends kcl.ac.uk.jian.building.building.Process
{
  /**
   * Returns the value of the '<em><b>Num</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' containment reference.
   * @see #setNum(Expression)
   * @see kcl.ac.uk.jian.building.building.BuildingPackage#getAddWindowProcess_Num()
   * @model containment="true"
   * @generated
   */
  Expression getNum();

  /**
   * Sets the value of the '{@link kcl.ac.uk.jian.building.building.AddWindowProcess#getNum <em>Num</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' containment reference.
   * @see #getNum()
   * @generated
   */
  void setNum(Expression value);

  /**
   * Returns the value of the '<em><b>Levels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Levels</em>' containment reference.
   * @see #setLevels(Expression)
   * @see kcl.ac.uk.jian.building.building.BuildingPackage#getAddWindowProcess_Levels()
   * @model containment="true"
   * @generated
   */
  Expression getLevels();

  /**
   * Sets the value of the '{@link kcl.ac.uk.jian.building.building.AddWindowProcess#getLevels <em>Levels</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Levels</em>' containment reference.
   * @see #getLevels()
   * @generated
   */
  void setLevels(Expression value);

} // AddWindowProcess
