/**
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.building;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see kcl.ac.uk.jian.building.building.BuildingFactory
 * @model kind="package"
 * @generated
 */
public interface BuildingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "building";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.kcl/uk/jian/building/Building";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "building";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BuildingPackage eINSTANCE = kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl.init();

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.BuildingProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.BuildingProgramImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getBuildingProgram()
   * @generated
   */
  int BUILDING_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Processes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILDING_PROGRAM__PROCESSES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILDING_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.ProcessImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 1;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.VariableDeclarationImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = PROCESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = PROCESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = PROCESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.AddFloorProcessImpl <em>Add Floor Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.AddFloorProcessImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getAddFloorProcess()
   * @generated
   */
  int ADD_FLOOR_PROCESS = 3;

  /**
   * The feature id for the '<em><b>Structure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FLOOR_PROCESS__STRUCTURE = PROCESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Levels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FLOOR_PROCESS__LEVELS = PROCESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Floor Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FLOOR_PROCESS_FEATURE_COUNT = PROCESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.PaintProcessImpl <em>Paint Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.PaintProcessImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getPaintProcess()
   * @generated
   */
  int PAINT_PROCESS = 4;

  /**
   * The feature id for the '<em><b>Levels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAINT_PROCESS__LEVELS = PROCESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAINT_PROCESS__COLOR = PROCESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Paint Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAINT_PROCESS_FEATURE_COUNT = PROCESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.AddWindowProcessImpl <em>Add Window Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.AddWindowProcessImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getAddWindowProcess()
   * @generated
   */
  int ADD_WINDOW_PROCESS = 5;

  /**
   * The feature id for the '<em><b>Num</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_WINDOW_PROCESS__NUM = PROCESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Levels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_WINDOW_PROCESS__LEVELS = PROCESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Window Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_WINDOW_PROCESS_FEATURE_COUNT = PROCESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.LoopImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 6;

  /**
   * The feature id for the '<em><b>Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__COUNT = PROCESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Processes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__PROCESSES = PROCESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = PROCESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.ExpressionImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.IntLiteralImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 8;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.RealLiteralImpl <em>Real Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.RealLiteralImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getRealLiteral()
   * @generated
   */
  int REAL_LITERAL = 9;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Real Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.IntVarExpressionImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.AdditionImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.impl.MultiplicationImpl
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link kcl.ac.uk.jian.building.building.WholeStructure <em>Whole Structure</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.ac.uk.jian.building.building.WholeStructure
   * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getWholeStructure()
   * @generated
   */
  int WHOLE_STRUCTURE = 13;


  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.BuildingProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see kcl.ac.uk.jian.building.building.BuildingProgram
   * @generated
   */
  EClass getBuildingProgram();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.ac.uk.jian.building.building.BuildingProgram#getProcesses <em>Processes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Processes</em>'.
   * @see kcl.ac.uk.jian.building.building.BuildingProgram#getProcesses()
   * @see #getBuildingProgram()
   * @generated
   */
  EReference getBuildingProgram_Processes();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see kcl.ac.uk.jian.building.building.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see kcl.ac.uk.jian.building.building.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link kcl.ac.uk.jian.building.building.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.ac.uk.jian.building.building.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link kcl.ac.uk.jian.building.building.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see kcl.ac.uk.jian.building.building.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.AddFloorProcess <em>Add Floor Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Floor Process</em>'.
   * @see kcl.ac.uk.jian.building.building.AddFloorProcess
   * @generated
   */
  EClass getAddFloorProcess();

  /**
   * Returns the meta object for the attribute '{@link kcl.ac.uk.jian.building.building.AddFloorProcess#getStructure <em>Structure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Structure</em>'.
   * @see kcl.ac.uk.jian.building.building.AddFloorProcess#getStructure()
   * @see #getAddFloorProcess()
   * @generated
   */
  EAttribute getAddFloorProcess_Structure();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.AddFloorProcess#getLevels <em>Levels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Levels</em>'.
   * @see kcl.ac.uk.jian.building.building.AddFloorProcess#getLevels()
   * @see #getAddFloorProcess()
   * @generated
   */
  EReference getAddFloorProcess_Levels();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.PaintProcess <em>Paint Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paint Process</em>'.
   * @see kcl.ac.uk.jian.building.building.PaintProcess
   * @generated
   */
  EClass getPaintProcess();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.PaintProcess#getLevels <em>Levels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Levels</em>'.
   * @see kcl.ac.uk.jian.building.building.PaintProcess#getLevels()
   * @see #getPaintProcess()
   * @generated
   */
  EReference getPaintProcess_Levels();

  /**
   * Returns the meta object for the attribute '{@link kcl.ac.uk.jian.building.building.PaintProcess#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see kcl.ac.uk.jian.building.building.PaintProcess#getColor()
   * @see #getPaintProcess()
   * @generated
   */
  EAttribute getPaintProcess_Color();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.AddWindowProcess <em>Add Window Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Window Process</em>'.
   * @see kcl.ac.uk.jian.building.building.AddWindowProcess
   * @generated
   */
  EClass getAddWindowProcess();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.AddWindowProcess#getNum <em>Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Num</em>'.
   * @see kcl.ac.uk.jian.building.building.AddWindowProcess#getNum()
   * @see #getAddWindowProcess()
   * @generated
   */
  EReference getAddWindowProcess_Num();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.AddWindowProcess#getLevels <em>Levels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Levels</em>'.
   * @see kcl.ac.uk.jian.building.building.AddWindowProcess#getLevels()
   * @see #getAddWindowProcess()
   * @generated
   */
  EReference getAddWindowProcess_Levels();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see kcl.ac.uk.jian.building.building.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.Loop#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Count</em>'.
   * @see kcl.ac.uk.jian.building.building.Loop#getCount()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Count();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.ac.uk.jian.building.building.Loop#getProcesses <em>Processes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Processes</em>'.
   * @see kcl.ac.uk.jian.building.building.Loop#getProcesses()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Processes();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see kcl.ac.uk.jian.building.building.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see kcl.ac.uk.jian.building.building.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link kcl.ac.uk.jian.building.building.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see kcl.ac.uk.jian.building.building.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Literal</em>'.
   * @see kcl.ac.uk.jian.building.building.RealLiteral
   * @generated
   */
  EClass getRealLiteral();

  /**
   * Returns the meta object for the attribute '{@link kcl.ac.uk.jian.building.building.RealLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see kcl.ac.uk.jian.building.building.RealLiteral#getVal()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_Val();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see kcl.ac.uk.jian.building.building.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link kcl.ac.uk.jian.building.building.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see kcl.ac.uk.jian.building.building.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see kcl.ac.uk.jian.building.building.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see kcl.ac.uk.jian.building.building.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link kcl.ac.uk.jian.building.building.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see kcl.ac.uk.jian.building.building.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.ac.uk.jian.building.building.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see kcl.ac.uk.jian.building.building.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link kcl.ac.uk.jian.building.building.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see kcl.ac.uk.jian.building.building.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link kcl.ac.uk.jian.building.building.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see kcl.ac.uk.jian.building.building.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link kcl.ac.uk.jian.building.building.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see kcl.ac.uk.jian.building.building.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.ac.uk.jian.building.building.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see kcl.ac.uk.jian.building.building.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for enum '{@link kcl.ac.uk.jian.building.building.WholeStructure <em>Whole Structure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Whole Structure</em>'.
   * @see kcl.ac.uk.jian.building.building.WholeStructure
   * @generated
   */
  EEnum getWholeStructure();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BuildingFactory getBuildingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.BuildingProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.BuildingProgramImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getBuildingProgram()
     * @generated
     */
    EClass BUILDING_PROGRAM = eINSTANCE.getBuildingProgram();

    /**
     * The meta object literal for the '<em><b>Processes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUILDING_PROGRAM__PROCESSES = eINSTANCE.getBuildingProgram_Processes();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.ProcessImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.VariableDeclarationImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.AddFloorProcessImpl <em>Add Floor Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.AddFloorProcessImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getAddFloorProcess()
     * @generated
     */
    EClass ADD_FLOOR_PROCESS = eINSTANCE.getAddFloorProcess();

    /**
     * The meta object literal for the '<em><b>Structure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_FLOOR_PROCESS__STRUCTURE = eINSTANCE.getAddFloorProcess_Structure();

    /**
     * The meta object literal for the '<em><b>Levels</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_FLOOR_PROCESS__LEVELS = eINSTANCE.getAddFloorProcess_Levels();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.PaintProcessImpl <em>Paint Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.PaintProcessImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getPaintProcess()
     * @generated
     */
    EClass PAINT_PROCESS = eINSTANCE.getPaintProcess();

    /**
     * The meta object literal for the '<em><b>Levels</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAINT_PROCESS__LEVELS = eINSTANCE.getPaintProcess_Levels();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAINT_PROCESS__COLOR = eINSTANCE.getPaintProcess_Color();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.AddWindowProcessImpl <em>Add Window Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.AddWindowProcessImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getAddWindowProcess()
     * @generated
     */
    EClass ADD_WINDOW_PROCESS = eINSTANCE.getAddWindowProcess();

    /**
     * The meta object literal for the '<em><b>Num</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_WINDOW_PROCESS__NUM = eINSTANCE.getAddWindowProcess_Num();

    /**
     * The meta object literal for the '<em><b>Levels</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_WINDOW_PROCESS__LEVELS = eINSTANCE.getAddWindowProcess_Levels();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.LoopImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__COUNT = eINSTANCE.getLoop_Count();

    /**
     * The meta object literal for the '<em><b>Processes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__PROCESSES = eINSTANCE.getLoop_Processes();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.ExpressionImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.IntLiteralImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.RealLiteralImpl <em>Real Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.RealLiteralImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getRealLiteral()
     * @generated
     */
    EClass REAL_LITERAL = eINSTANCE.getRealLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__VAL = eINSTANCE.getRealLiteral_Val();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.IntVarExpressionImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.AdditionImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.impl.MultiplicationImpl
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link kcl.ac.uk.jian.building.building.WholeStructure <em>Whole Structure</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.ac.uk.jian.building.building.WholeStructure
     * @see kcl.ac.uk.jian.building.building.impl.BuildingPackageImpl#getWholeStructure()
     * @generated
     */
    EEnum WHOLE_STRUCTURE = eINSTANCE.getWholeStructure();

  }

} //BuildingPackage
