/**
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.building;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see kcl.ac.uk.jian.building.building.BuildingPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
