/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class BuildingProposalProvider extends AbstractBuildingProposalProvider {
}
