/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.parser.antlr;

import com.google.inject.Inject;
import kcl.ac.uk.jian.building.parser.antlr.internal.InternalBuildingParser;
import kcl.ac.uk.jian.building.services.BuildingGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BuildingParser extends AbstractAntlrParser {

	@Inject
	private BuildingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBuildingParser createParser(XtextTokenStream stream) {
		return new InternalBuildingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BuildingProgram";
	}

	public BuildingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BuildingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
