/*
 * generated by Xtext 2.20.0
 */
package kcl.ac.uk.jian.building.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BuildingUiModule extends AbstractBuildingUiModule {

	public BuildingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
